# Generated by Django 5.1.3 on 2024-11-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='urgency',
            field=models.CharField(default='low', max_length=10),
        ),
    ]
